import { v4 as uuidv4 } from 'uuid';

/**
 * Extracts domain from Bitwarden description in any language
 * Examples:
 * - "Webbplats: dash.cloudflare.com. Genererad av Bitwarden." -> "dash.cloudflare.com"
 * - "Website: example.com. Generated by Bitwarden." -> "example.com"
 */
function extractDomainFromDescription(description) {
  if (!description || typeof description !== 'string') {
    return null;
  }

  // Try to find a domain pattern (e.g., subdomain.domain.tld or domain.tld)
  // Look for patterns like "something.domain.com" or "domain.com"
  const domainPattern = /([a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\.[a-zA-Z]{2,})/;
  const match = description.match(domainPattern);
  
  if (match && match[1]) {
    return match[1];
  }
  
  return null;
}

/**
 * Extracts the base domain (without TLD) from a full domain
 * Uses a pattern-based approach that works with all TLDs (single or multi-part)
 * Examples:
 * - "dash.cloudflare.com" -> "cloudflare"
 * - "example.com" -> "example"
 * - "sub.example.co.uk" -> "example"
 * - "test.example.org" -> "example"
 * - "a.b.example.co.uk" -> "example"
 */
function getBaseDomain(domain) {
  if (!domain) {
    return null;
  }

  // Split domain into parts
  const parts = domain.split('.');
  
  // For domains with 2 parts (e.g., "example.com"), return the first part
  if (parts.length === 2) {
    return parts[0];
  }
  
  // For domains with 3+ parts, extract the main domain part
  // Strategy: TLDs are typically 1-2 parts, so we look for the part before the TLD
  // - "sub.example.com" (3 parts) -> parts[1] = "example" (before .com)
  // - "sub.example.co.uk" (4 parts) -> parts[1] = "example" (before .co.uk)
  // - "a.b.example.co.uk" (5 parts) -> parts[2] = "example" (before .co.uk)
  
  // For most real-world cases, the base domain is the second-to-last part
  // This works for both single-part TLDs (.com, .org) and two-part TLDs (.co.uk, .com.au)
  // For longer subdomain chains, we go back one more level
  if (parts.length === 3) {
    // sub.example.com -> "example"
    return parts[1];
  } else if (parts.length >= 4) {
    // sub.example.co.uk -> "example"
    // a.b.example.co.uk -> "example"
    // We use the third-to-last part to handle two-part TLDs
    return parts[parts.length - 3];
  }
  
  // Fallback: return first part
  return parts[0];
}

export function generateAlias(domain, description = null) {
  if (!domain) {
    throw new Error('Domain is required');
  }
  
  const randomPart = uuidv4().split('-')[0]; // short random ID
  
  // Try to extract domain from description and get base domain part
  let baseDomainPart = null;
  if (description) {
    const extractedDomain = extractDomainFromDescription(description);
    if (extractedDomain) {
      baseDomainPart = getBaseDomain(extractedDomain);
    }
  }
  
  // Format: random-string-base-domain@domain or random-string@domain
  const localPart = baseDomainPart 
    ? `${randomPart}-${baseDomainPart}`
    : randomPart;
  
  return `${localPart}@${domain}`;
}
