import { describe, it, expect } from 'vitest'
import { extractDomainFromDescription } from '../../src/index.js'

describe('extractDomainFromDescription', () => {
  it('extracts a domain from an English Bitwarden description', () => {
    expect(extractDomainFromDescription('Website: example.com. Generated by Bitwarden.')).toBe(
      'example.com'
    )
  })

  it('extracts a domain from a Swedish Bitwarden description', () => {
    expect(
      extractDomainFromDescription('Webbplats: dash.cloudflare.com. Genererad av Bitwarden.')
    ).toBe('dash.cloudflare.com')
  })

  it('extracts a subdomain', () => {
    expect(extractDomainFromDescription('Website: news.ycombinator.com. Generated by Bitwarden.')).toBe(
      'news.ycombinator.com'
    )
  })

  it('returns null for null input', () => {
    expect(extractDomainFromDescription(null)).toBeNull()
  })

  it('returns null for undefined input', () => {
    expect(extractDomainFromDescription(undefined)).toBeNull()
  })

  it('returns null when no domain is present', () => {
    expect(extractDomainFromDescription('No domain here')).toBeNull()
  })

  it('returns null for a non-string input', () => {
    expect(extractDomainFromDescription(42)).toBeNull()
  })

  it('handles a plain domain string (no surrounding text)', () => {
    expect(extractDomainFromDescription('github.com')).toBe('github.com')
  })

  it('returns null for Swedish boilerplate with no URL (Genererad av Bitwarden.)', () => {
    expect(extractDomainFromDescription('Genererad av Bitwarden.')).toBeNull()
  })

  it('returns null for English boilerplate with no URL (Generated by Bitwarden.)', () => {
    expect(extractDomainFromDescription('Generated by Bitwarden.')).toBeNull()
  })
})
