import { vi, describe, it, expect, beforeEach } from 'vitest'
import request from 'supertest'

vi.mock('../../src/stalwart.js', () => ({
  addAliasToStalwart: vi.fn(),
}))

vi.mock('../../src/logger.js', () => ({ log: vi.fn(), logFile: '/dev/null' }))

vi.mock('../../src/config.js', () => ({
  default: { port: 3000, stalwartUrl: 'https://stalwart.example.com' },
}))

import { addAliasToStalwart } from '../../src/stalwart.js'
import { app } from '../../src/index.js'

const AUTH = 'Bearer test-token'
const TOKEN = 'test-token'

describe('POST /api/v1/aliases', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('authentication', () => {
    it('returns 401 when Authorization header is missing', async () => {
      const res = await request(app).post('/api/v1/aliases').send({ domain: 'example.com' })
      expect(res.status).toBe(401)
      expect(res.body.error).toMatch(/API key/i)
      expect(addAliasToStalwart).not.toHaveBeenCalled()
    })

    it('returns 401 when the API key field is empty (bare Bearer scheme)', async () => {
      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', 'Bearer')
        .send({ domain: 'example.com' })
      expect(res.status).toBe(401)
      expect(addAliasToStalwart).not.toHaveBeenCalled()
    })

    it('strips the Bearer scheme before handing the key to Stalwart', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })
      await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })
      expect(addAliasToStalwart).toHaveBeenCalledWith(
        'example.com',
        TOKEN,
        null,
        expect.any(Object)
      )
    })

    it('accepts a bare key with no scheme, which is what Bitwarden sends', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })
      await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', 'API_rawkey')
        .send({ domain: 'example.com' })
      expect(addAliasToStalwart).toHaveBeenCalledWith(
        'example.com',
        'API_rawkey',
        null,
        expect.any(Object)
      )
    })
  })

  describe('validation', () => {
    it('returns 400 when domain is missing', async () => {
      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({})
      expect(res.status).toBe(400)
      expect(res.body.error).toMatch(/domain/i)
    })
  })

  describe('success', () => {
    it('returns 201 with the correct response shape', async () => {
      addAliasToStalwart.mockResolvedValue({
        email: 'abc123@example.com',
        id: 'srv-id-42',
      })

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(201)
      expect(res.body.data).toMatchObject({
        id: 'srv-id-42',
        email: 'abc123@example.com',
        local_part: 'abc123',
        domain: 'example.com',
        enabled: true,
      })
    })

    it('includes the description field when Bitwarden sends one', async () => {
      addAliasToStalwart.mockResolvedValue({
        email: 'abc123@example.com',
        id: 'srv-id-42',
      })

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({
          domain: 'example.com',
          description: 'Website: github.com. Generated by Bitwarden.',
        })

      expect(res.status).toBe(201)
      // description cleaned to just the extracted domain
      expect(res.body.data.description).toBe('github.com')
    })

    it('sends null description to Stalwart when Bitwarden description is boilerplate-only (no URL)', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@peekoff.com', id: 'id1' })

      await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({
          domain: 'peekoff.com',
          description: 'Genererad av Bitwarden.',
        })

      expect(addAliasToStalwart).toHaveBeenCalledWith(
        'peekoff.com',
        TOKEN,
        null,
        expect.any(Object)
      )
    })

    it('returns null description in response when Bitwarden sends boilerplate-only description', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@peekoff.com', id: 'id1' })

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({
          domain: 'peekoff.com',
          description: 'Generated by Bitwarden.',
        })

      expect(res.status).toBe(201)
      expect(res.body.data.description).toBeNull()
    })

    it('passes the cleaned description (not the full Bitwarden boilerplate) to Stalwart', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })

      await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({
          domain: 'example.com',
          description: 'Website: github.com. Generated by Bitwarden.',
        })

      expect(addAliasToStalwart).toHaveBeenCalledWith(
        'example.com',
        TOKEN,
        'github.com',
        expect.objectContaining({ forDomain: 'github.com' })
      )
    })
  })

  describe('error handling', () => {
    it('returns 500 when Stalwart throws', async () => {
      addAliasToStalwart.mockRejectedValue(new Error('JMAP session discovery failed'))

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(500)
      expect(res.body.error).toMatch(/JMAP session discovery failed/)
    })

    it('passes a 401 from Stalwart through instead of masking it as 500', async () => {
      addAliasToStalwart.mockRejectedValue(
        Object.assign(new Error('Stalwart rejected the API key (HTTP 401)'), { status: 401 })
      )

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(401)
    })

    it('passes a 403 from Stalwart through instead of masking it as 500', async () => {
      addAliasToStalwart.mockRejectedValue(
        Object.assign(new Error('needs the sysMaskedEmailCreate permission'), { status: 403 })
      )

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(403)
      expect(res.body.error).toMatch(/sysMaskedEmailCreate/)
    })

    it('returns 500 when Stalwart returns no email', async () => {
      addAliasToStalwart.mockResolvedValue({ id: 'id1' }) // no .email

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(500)
    })
  })

  describe('route aliases', () => {
    it('also responds on /api/aliases', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })
      const res = await request(app)
        .post('/api/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })
      expect(res.status).toBe(201)
    })

    it('also responds on /api/aliases/api/v1/aliases', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })
      const res = await request(app)
        .post('/api/aliases/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })
      expect(res.status).toBe(201)
    })
  })
})
