import { vi, describe, it, expect, beforeEach } from 'vitest'
import request from 'supertest'

vi.mock('../../src/stalwart.js', () => ({
  addAliasToStalwart: vi.fn(),
}))

vi.mock('../../src/logger.js', () => ({ log: vi.fn(), logFile: '/dev/null' }))

vi.mock('../../src/config.js', () => ({
  default: { port: 3000, stalwartUrl: 'https://stalwart.example.com' },
}))

import { addAliasToStalwart } from '../../src/stalwart.js'
import { app } from '../../src/index.js'

const AUTH = 'Bearer test-token'

describe('POST /api/v1/aliases', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('authentication', () => {
    it('returns 401 when Authorization header is missing', async () => {
      const res = await request(app).post('/api/v1/aliases').send({ domain: 'example.com' })
      expect(res.status).toBe(401)
      expect(res.body.error).toMatch(/Authorization/i)
    })
  })

  describe('validation', () => {
    it('returns 400 when domain is missing', async () => {
      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({})
      expect(res.status).toBe(400)
      expect(res.body.error).toMatch(/domain/i)
    })
  })

  describe('success', () => {
    it('returns 201 with the correct response shape', async () => {
      addAliasToStalwart.mockResolvedValue({
        email: 'abc123@example.com',
        id: 'srv-id-42',
      })

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(201)
      expect(res.body.data).toMatchObject({
        id: 'srv-id-42',
        email: 'abc123@example.com',
        local_part: 'abc123',
        domain: 'example.com',
        enabled: true,
      })
    })

    it('includes the description field when Bitwarden sends one', async () => {
      addAliasToStalwart.mockResolvedValue({
        email: 'abc123@example.com',
        id: 'srv-id-42',
      })

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({
          domain: 'example.com',
          description: 'Website: github.com. Generated by Bitwarden.',
        })

      expect(res.status).toBe(201)
      // description cleaned to just the extracted domain
      expect(res.body.data.description).toBe('github.com')
    })

    it('passes the cleaned description (not the full Bitwarden boilerplate) to Stalwart', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })

      await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({
          domain: 'example.com',
          description: 'Website: github.com. Generated by Bitwarden.',
        })

      expect(addAliasToStalwart).toHaveBeenCalledWith(
        'example.com',
        AUTH,
        'github.com',
        expect.objectContaining({ forDomain: 'github.com', createdBy: 'Bitwarden' })
      )
    })
  })

  describe('error handling', () => {
    it('returns 500 when Stalwart throws', async () => {
      addAliasToStalwart.mockRejectedValue(new Error('JMAP session discovery failed'))

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(500)
      expect(res.body.error).toMatch(/JMAP session discovery failed/)
    })

    it('returns 500 when Stalwart returns no email', async () => {
      addAliasToStalwart.mockResolvedValue({ id: 'id1' }) // no .email

      const res = await request(app)
        .post('/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })

      expect(res.status).toBe(500)
    })
  })

  describe('route aliases', () => {
    it('also responds on /api/aliases', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })
      const res = await request(app)
        .post('/api/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })
      expect(res.status).toBe(201)
    })

    it('also responds on /api/aliases/api/v1/aliases', async () => {
      addAliasToStalwart.mockResolvedValue({ email: 'x@example.com', id: 'id1' })
      const res = await request(app)
        .post('/api/aliases/api/v1/aliases')
        .set('Authorization', AUTH)
        .send({ domain: 'example.com' })
      expect(res.status).toBe(201)
    })
  })
})
